### ISSUE TITLE
状态显示【检测中…】

### ISSUE THREAD

**Issue by naruto1995** [Nevolution/nevolution.github.io#1]
之前已用adb命令开启【增强模式】，重启后状态显示【检测中…】

是重启后导致adb命令失效了吗？

**Comment by oasisfeng** [comment]
v5.5 版本已修正。

**Comment by naruto1995** [comment]
> v5.5 版本已修正。

请问何时发布更新呢？Play商店也还是v5.3.5

**Comment by oasisfeng** [comment]
已发布到酷安市场。

Google Play 市场的审核发生了意外（插件推荐被 Google 误判为广告……），需要修改后重新提交。
